name: Zowe SDK Release

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release-dev') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.ZOWE_ROBOT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Increment dev version
        id: update-version
        shell: python
        run: |
          import sys
          sys.path.append("src")
          from _version import __version__
          prerelease_tag = "dev"
          tag_end_index = __version__.index(prerelease_tag) + len(prerelease_tag)
          new_version = __version__[:tag_end_index] + str(int(__version__[tag_end_index:]) + 1)
          with open("src/_version.py", 'w') as f:
            f.write("__version__ = \"" + new_version + "\"\n")
          print("::set-output name=version::" + new_version)
          print("::set-output name=cargo-version::" + "-".join(new_version.rsplit(".", 1)))

      - name: Increment dev version (cargo)
        run: cargo install cargo-edit && cargo set-version ${{ steps.update-version.outputs.cargo-version }}
        working-directory: src/secrets

      - name: Build dist wheels
        run: bash build.sh

      - name: Commit version update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "Bump version to ${{ steps.update-version.outputs.version }} [ci skip]"
          commit_options: "--signoff"
          commit_user_name: ${{ secrets.ZOWE_ROBOT_USER }}
          commit_user_email: ${{ secrets.ZOWE_ROBOT_EMAIL }}
          file_pattern: "src/_version.py src/secrets/Cargo.*"
          tagging_message: v${{ steps.update-version.outputs.version }}

      - name: Publish packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_ROBOT_TOKEN }}
